import { chromium } from 'playwright';
const B=process.env.BASE??'http://localhost:3299';
const b=await chromium.launch(); const p=await b.newPage();
const errs=[]; p.on('console',m=>m.type()==='error'&&errs.push(m.text()+' '+(m.location()?.url??''))); p.on('pageerror',e=>errs.push(e.message));
p.on('response',r=>r.status()>=400&&errs.push(r.status()+' '+r.url()));
await p.goto(B+'/sobre',{waitUntil:'networkidle'});
await p.locator('body').click({position:{x:5,y:300}});
const t0=Date.now(); await p.keyboard.press('Control+k');
for (let i=0;i<40;i++){ if(await p.getByRole('dialog').isVisible()) break; await p.waitForTimeout(100);} console.log('first Ctrl+K dialog after', Date.now()-t0,'ms visible=',await p.getByRole('dialog').isVisible());
await p.keyboard.press('Escape'); await p.waitForTimeout(300);
await p.keyboard.press('Control+k'); await p.waitForTimeout(300); console.log('second Ctrl+K visible', await p.getByRole('dialog').isVisible());
await p.keyboard.press('Escape'); await p.waitForTimeout(300);
await p.evaluate(()=>localStorage.setItem('radar-mde:recent-search','{bad json'));
await p.keyboard.press('Control+k'); await p.waitForTimeout(500); console.log('after corrupt recents visible', await p.getByRole('dialog').isVisible(), errs);
await p.keyboard.press('Escape');
// fresh page: press ctrl+k immediately before hydration?
const p2=await b.newPage(); await p2.goto(B+'/sobre',{waitUntil:'domcontentloaded'}); await p2.keyboard.press('Control+k'); await p2.waitForTimeout(1500); console.log('early Ctrl+K visible', await p2.getByRole('dialog').isVisible());
const p3=await b.newPage({viewport:{width:375,height:812}}); await p3.goto(B+'/',{waitUntil:'networkidle'});
console.log('mobile header links', await p3.locator('header a, header button').evaluateAll(es=>es.filter(e=>e.offsetParent).map(e=>(e.innerText||e.getAttribute('aria-label')).trim())));
await p3.screenshot({path:'reports/functional/shots/r2-mobile-header.png'});
await b.close();
