import { chromium } from "playwright";
const b = await chromium.launch();
const ctx = await b.newContext({ permissions: ["clipboard-read", "clipboard-write"] });
const p = await ctx.newPage();
const errs = []; p.on("pageerror", e => errs.push(e.message.slice(0,200)));
await p.goto("http://localhost:3210/sp/franca", { waitUntil: "networkidle" });
await p.getByLabel(/Seu nome/).fill("Maria Silva");
const ta = () => p.locator("[role=tabpanel] textarea:visible");
await ta().evaluate((el) => el.scrollTop = 1e6);
await ta().press("End"); await ta().type("\nP.S. teste");
const tabs = p.locator("[role=tab]");
await tabs.nth(2).click(); await p.waitForTimeout(200);
console.log("vereador signed:", (await ta().inputValue()).includes("Maria Silva") ? "(n/a: vereador has own placeholder)" : "no name (expected)");
await tabs.nth(0).click(); await p.waitForTimeout(200);
const v = await ta().inputValue();
console.log("edit kept:", v.includes("P.S. teste"), "name filled:", v.includes("Maria Silva"), "tab label:", await tabs.nth(0).innerText());
const href = await p.getByRole("button", { name: "E-mail" }).getAttribute("href");
console.log("mailto length:", href.length);
await p.getByRole("button", { name: "E-mail" }).evaluate((a) => a.addEventListener("click", (e) => e.preventDefault()));
await p.getByRole("button", { name: "E-mail" }).click(); await p.waitForTimeout(300);
console.log("clipboard has letter:", (await p.evaluate(() => navigator.clipboard.readText())).includes("P.S. teste"));
console.log("hint:", await p.locator("[role=tabpanel] [role=status]:visible").innerText());
console.log(errs);
await b.close();
